import type { ComponentType } from 'react'
import {
  Ai21,
  Ai360,
  AlephAlpha,
  Alibaba,
  AntGroup,
  Arcee,
  AssemblyAI,
  Aws,
  Azure,
  BAAI,
  Baichuan,
  Baidu,
  Bedrock,
  Bfl,
  ByteDance,
  Claude,
  Cohere,
  Coqui,
  Dbrx,
  DeepSeek,
  ElevenLabs,
  EssentialAI,
  Fireworks,
  FishAudio,
  Google,
  Grok,
  Groq,
  Haiper,
  Hedra,
  IBM,
  Ideogram,
  Inception,
  Inflection,
  InternLM,
  Jina,
  Kling,
  Kwaipilot,
  Liquid,
  LLaVA,
  LongCat,
  Luma,
  Meta,
  Microsoft,
  Midjourney,
  Minimax,
  Mistral,
  Moonshot,
  Morph,
  MyShell,
  NousResearch,
  NovelAI,
  Nvidia,
  Ollama,
  OpenAI,
  OpenChat,
  OpenRouter,
  Perplexity,
  Pika,
  PixVerse,
  Qwen,
  Recraft,
  Runway,
  Rwkv,
  SenseNova,
  Skywork,
  Spark,
  Stability,
  Stepfun,
  Suno,
  Tencent,
  TII,
  Together,
  Tripo,
  Upstage,
  Vidu,
  Voyage,
  Xuanyuan,
  Yandex,
  Yi,
  Zhipu,
} from '@lobehub/icons'
import { resolveByDashPrefix } from './dash-prefix-lookup'
import {
  iconFileForVendor,
  type VendorIconFileEntry,
} from './vendor-icon-files'

export type VendorIconComponent = ComponentType<{ className?: string }>

/**
 * vendor/provider slug -> 本地打包的品牌图标组件(离线可用)。
 * 未覆盖的 slug 由 vendor-icon-files 的本地静态 SVG（public/model-icons）与
 * monogram 逐级兜底,视觉与云端价格表 providers 字典下发的 icon 一致。
 */
const VENDOR_ICON_COMPONENTS: Record<string, VendorIconComponent> = {
  // 主力厂商(与云端价格表 vendor slug 对齐)
  anthropic: Claude.Color,
  openai: OpenAI,
  google: Google.Color,
  meta: Meta.Color,
  deepseek: DeepSeek.Color,
  alibaba: Alibaba.Color,
  qwen: Qwen.Color,
  mistral: Mistral.Color,
  xai: Grok,
  cohere: Cohere.Color,
  ai21: Ai21.BrandColor,
  moonshotai: Moonshot,
  zhipuai: Zhipu.Color,
  minimax: Minimax.Color,
  perplexity: Perplexity.Color,
  stepfun: Stepfun,
  baidu: Baidu.Color,
  tencent: Tencent.Color,
  bytedance: ByteDance.Color,
  '01-ai': Yi.Color,
  nvidia: Nvidia.Color,
  ibm: IBM,
  liquid: Liquid,
  amazon: Aws.Color,
  inception: Inception,
  morph: Morph.Color,
  '360': Ai360.Color,
  microsoft: Microsoft.Color,
  iflytek: Spark.Color,
  tii: TII.Color,
  jina: Jina,
  voyage: Voyage.Color,
  baai: BAAI,
  bfl: Bfl,
  kling: Kling.Color,
  recraft: Recraft,
  longcat: LongCat.Color,
  // LobeHub 品牌兜底集
  alephalpha: AlephAlpha,
  antgroup: AntGroup.Color,
  arcee: Arcee.Color,
  assemblyai: AssemblyAI.Color,
  baichuan: Baichuan.Color,
  coqui: Coqui.Color,
  databricks: Dbrx.Color,
  elevenlabs: ElevenLabs,
  essentialai: EssentialAI.Color,
  fishaudio: FishAudio,
  haiper: Haiper,
  hedra: Hedra,
  ideogram: Ideogram,
  inflection: Inflection,
  internlm: InternLM.Color,
  kwaipilot: Kwaipilot.Color,
  llava: LLaVA.Color,
  luma: Luma.Color,
  midjourney: Midjourney,
  myshell: MyShell.Color,
  nousresearch: NousResearch,
  novelai: NovelAI,
  openchat: OpenChat.Color,
  pika: Pika,
  pixverse: PixVerse.Color,
  runway: Runway,
  rwkv: Rwkv.Color,
  sensenova: SenseNova.Color,
  skywork: Skywork.Color,
  stability: Stability.Color,
  suno: Suno,
  tripo: Tripo.Color,
  upstage: Upstage.Color,
  vidu: Vidu.Color,
  xuanyuan: Xuanyuan.Color,
  yandex: Yandex,
  // 常见 provider 渠道(供应商价格对比等场景)
  openrouter: OpenRouter,
  groq: Groq,
  azure: Azure.Color,
  together: Together.Color,
  'together-ai': Together.Color,
  fireworks: Fireworks.Color,
  'fireworks-ai': Fireworks.Color,
  ollama: Ollama,
  bedrock: Bedrock.Color,
  'amazon-bedrock': Bedrock.Color,
  'google-vertex': Google.Color,
}

/** slug 精确命中 -> 最长 dash 前缀家族回退(与 SVG 映射规则一致) */
export function getVendorIconComponent(
  slug: string
): VendorIconComponent | null {
  return resolveByDashPrefix(slug, VENDOR_ICON_COMPONENTS)
}

export interface ModelVendorEntry {
  vendor: string
  /** 本地打包的图标组件(可能为空,走静态 SVG/monogram 兜底) */
  icon: VendorIconComponent | null
  /** public/model-icons 下的静态 SVG */
  iconFile: VendorIconFileEntry | null
}

/** 按 vendor slug 组装图标条目 */
export function getVendorEntry(vendor: string): ModelVendorEntry {
  return {
    vendor,
    icon: getVendorIconComponent(vendor),
    iconFile: iconFileForVendor(vendor),
  }
}
